name: Build Example App with Android Gradle Plugin

run-name: Build Example App with Android Gradle Plugin

on:
  workflow_dispatch:
  # TODO(radoslawrolka): enable on push/pr once published more libs
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build-example-app:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ— Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: ğŸ— Build Example App
        run: bun create expo example-app

      # Todo(radoslawrolka): Change this step to use remote expo-plugin once it's published
      # - name: ğŸš§ Prepare Example App
      #   run: bunx expo install @rnrepo/expo-config-plugin
      #   working-directory: example-app

      - name: ğŸ›  Expo Prebuild for Android
        run: bun expo prebuild -p android
        working-directory: example-app

      - name: ğŸ— Build Example App with Android Gradle Plugin
        run: ./gradlew assembleDebug --configure-on-demand
        working-directory: example-app/android
