name: Build Example App with Android Gradle Plugin

run-name: Build Example App with Android Gradle Plugin

on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/**'
      - 'packages/expo-config-plugin/**'
      - '.github/workflows/build-example-app.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/client/**'
      - 'packages/expo-config-plugin/**'
      - '.github/workflows/build-example-app.yml'

jobs:
  build-example-app:
    runs-on: rnrepo-builder-ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
    env:
      EXAMPLE_APP: example-app
    concurrency:
      group: build-example-app-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: â˜• Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ“± Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: âœ… Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: ğŸ— Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: ğŸ— Create Example App
        run: bun create expo ${{ env.EXAMPLE_APP }}

      - name: ğŸ“¦ Install @rnrepo/expo-config-plugin
        run: bunx expo install @rnrepo/expo-config-plugin
        working-directory: ${{ env.EXAMPLE_APP }}

      - name: ğŸ›  Add @rnrepo/expo-config-plugin to app.json plugins
        run: jq '.expo.plugins += ["@rnrepo/expo-config-plugin"]' app.json > /tmp/app.json && mv /tmp/app.json app.json
        working-directory: ${{ env.EXAMPLE_APP }}

      - name: ğŸ›  Expo Prebuild for Android
        run: bun expo prebuild -p android
        working-directory: ${{ env.EXAMPLE_APP }}

      - name: ğŸ— Build Example App with RNRepo
        run: ./gradlew :app:assembleDebug --configure-on-demand --info
        working-directory: ${{ env.EXAMPLE_APP }}/android
