name: Build Example App with Android Gradle Plugin

run-name: Build Example App with Android Gradle Plugin

on:
  workflow_dispatch:
    inputs:
      maven_repository_type:
        description: 'Releases or Snapshots Maven repository type'
        type: choice
        options:
          - releases
          - snapshots
        required: true
        default: 'releases'
      rnrepo_prebuilds_plugin_version:
        description: 'RNRepo prebuilds-plugin version'
        required: false
        type: string
        default: '0.2.0'
      libraries:
        description: 'libraries with versions to install, format: libraryName1@version1,libraryName2@version2'
        required: true
        type: string
      react_native_version:
        description: 'React Native version'
        required: true
        type: string

jobs:
  build-example-app:
    runs-on: rnrepo-builder-ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: read
      contents: read
    env:
      EXAMPLE_APP: exampleApp

    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: â˜• Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ“± Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: âœ… Accept Android Licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: ğŸ— Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: ğŸ— Create Example App
        run: bunx @react-native-community/cli@latest init ${{ env.EXAMPLE_APP }} --version ${{ github.event.inputs.react_native_version }}

      - name: ğŸ“¦ Install your packages to test
        run: |
          IFS=',' read -ra LIBS <<< "${{ github.event.inputs.libraries }}"
          for lib in "${LIBS[@]}"; do
            bun install "$lib" --save-exact
          done
        working-directory: ${{ env.EXAMPLE_APP }}

      - name: ğŸ›  Add RNRepo to gradle
        run: bun run .github/workflows/scripts/applyRNRepoAndroid.ts ${{ env.EXAMPLE_APP }}/android ${{ github.event.inputs.rnrepo_prebuilds_plugin_version }} ${{ github.event.inputs.maven_repository_type }}

      - name: ğŸ— Build Example App with RNRepo
        run: ./gradlew :app:assembleDebug --info --no-daemon
        working-directory: ${{ env.EXAMPLE_APP }}/android
