name: Publish Expo Config Plugin to npm

run-name: Publish @rnrepo/expo-config-plugin to npm

on:
  workflow_dispatch:

jobs:
  publish-expo-config-plugin:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    env:
      PACKAGE_NAME: PLACEHOLDER # Will be set later
      PLUGIN_DIR: packages/expo-config-plugin

    steps:
      - name: üèó Checkout repository
        uses: actions/checkout@v4

      - name: üèó Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: üèó Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: üì¶ Install dependencies
        run: bun install

      - name: üî® Build plugin
        run: bun run build
        working-directory: ${{ env.PLUGIN_DIR }}

      - name: üî® Prepare package
        run: bun run prepare
        working-directory: ${{ env.PLUGIN_DIR }}

      - name: üî® Create npm package
        run: npm pack
        working-directory: ${{ env.PLUGIN_DIR }}

      - name: üè∑Ô∏è Set PACKAGE_NAME env variable
        run: echo "PACKAGE_NAME=$(ls -l | egrep -o "rnrepo-expo-config-plugin-(.*)(=?\.tgz)" )" >> $GITHUB_ENV
        working-directory: ${{ env.PLUGIN_DIR }}

      - name: ‚ùå Fail if PACKAGE_NAME is not set
        if: ${{ env.PACKAGE_NAME == 'PLACEHOLDER' }}
        run: exit 1 # This should never happen.

      - name: üöÄ Publish to npm
        run: npm publish $PACKAGE_NAME --tag nightly
        working-directory: ${{ env.PLUGIN_DIR }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
