name: Publish Expo Config Plugin to npm

run-name: Publish @rnrepo/expo-config-plugin to npm

on:
  workflow_dispatch:

jobs:
  publish-expo-config-plugin:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    defaults:
    env:
      TAG: expo-config-plugin
      VERSION: PLACEHOLDER # Will be set later
      PLUGIN_DIR: packages/expo-config-plugin

    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ— Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: ğŸ”¨ Build plugin
        run: bun run build

      - name: ğŸ”¨ Prepare package
        run: bun run prepare
        working-directory: ${{ env.PLUGIN_DIR }}

      - name: ğŸ·ï¸ Set VERSION env variable
        run: echo "VERSION=$(node -e "console.log(require('./package.json').version)")" >> $GITHUB_ENV
        working-directory: ${{ env.PLUGIN_DIR }}

      - name: âŒ Fail if VERSION is not set
        if: ${{ env.VERSION == 'PLACEHOLDER' }}
        run: exit 1 # This should never happen.

      # - name: ğŸ·ï¸ Create Git tag
      #   run: |
      #     git tag "${{ env.TAG }}-v${{ env.VERSION }}"
      #     git push origin "${{ env.TAG }}-v${{ env.VERSION }}"

      - name: ğŸ“¦ Move package to workspace root
        # Running `--provenance` in the workspace breaks.
        run: mv ${{ env.PLUGIN_DIR }} .

      - name: ğŸš€ Publish to npm
        run: bunx publish --provenance
