name: Publish React Native Library for Android

run-name: Publish library for Android from build workflow

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Build workflow run ID (for testing)'
        required: true
        type: string
  # TODO: eventually this action will run as a response to a workflow_run event
  # workflow_run:
  #   workflows: ["Build React Native Library for Android"]
  #   types:
  #     - completed

jobs:
  publish-library:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: üèó Checkout repository
        uses: actions/checkout@v4

      - name: üì• Download Maven artifacts (from workflow_run)
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: üì• Download Maven artifacts (from workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ inputs.build_run_id }}

      - name: üèó Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: üì¶ Install dependencies
        run: bun install

      - name: üì§ Publish library
        run: bun run packages/publisher/publish-library-android.ts -- "${{ github.event_name == 'workflow_run' && github.event.workflow_run.id || inputs.build_run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          MAVEN_USERNAME: ${{ secrets.RNREPO_SWM_PUBLISHER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.RNREPO_SWM_PUBLISHER_TOKEN }}
          MAVEN_REPOSITORY_URL: https://packages.rnrepo.org/snapshots

