name: Publish Expo Config Plugin to npm

run-name: Publish @rnrepo/expo-config-plugin to npm

on:
  workflow_dispatch:

jobs:
  publish-expo-config-plugin:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    defaults:
      run:
        working-directory: ./packages/expo-config-plugin

    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ— Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: ğŸ”¨ Build plugin
        run: bun run build

      - name: ğŸ”¨ Prepare package
        run: bun run prepare

      - name: ğŸ·ï¸ Set VERSION env variable
        run: echo "VERSION=$(node -e "console.log(require('./package.json').version)")" >> $GITHUB_ENV

      - name: bunx whoami
        run: bunx whoami
    
      - name: âŒ Fail if VERSION is not set
        if: ${{ env.VERSION == '' }}
        run: exit 1 # This should never happen.

      # - name: ğŸ·ï¸ Create Git tag
      #   run: |
      #     git tag "expo-config-plugin-v${{ env.VERSION }}"
      #     git push origin "expo-config-plugin-v${{ env.VERSION }}"

      # TODO: Temporary use tag nightly
      - name: ğŸš€ Publish to npm
        run: bunx publish --provenance
