name: Publish React Native Library

run-name: Publish library from build workflow

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Build workflow run ID to download artifacts from'
        required: true
        type: string
  # TODO: eventually this action will run as a response to a workflow_run event
  # workflow_run:
  #   workflows: ["Build React Native Library for Android"]
  #   types:
  #     - completed

jobs:
  publish-library:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“¥ Download Maven artifacts (from workflow_run)
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          path: ~/.m2/repository/org/rnrepo/public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: ğŸ“¥ Download Maven artifacts (from workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/download-artifact@v4
        with:
          path: ~/.m2/repository/org/rnrepo/public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ inputs.build_run_id }}

      - name: ğŸ— Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: ğŸ“¦ Install dependencies
        run: bun install

      - name: ğŸ“¤ Publish library
        run: bun run packages/publisher/publish-library-android.ts

