name: Publish Expo Config Plugin to npm

run-name: Publish @rnrepo/expo-config-plugin to npm

on:
  workflow_dispatch:

jobs:
  publish-expo-config-plugin:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./packages/expo-config-plugin

    steps:
      - name: üèó Checkout repository
        uses: actions/checkout@v4

      - name: üèó Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: üì¶ Install dependencies
        run: bun install

      - name: üî® Build plugin
        run: bun run build

      - name: üî® Prepare package
        run: bun run prepare

      - name: üìÉ Create package tarball
        run: npm pack

      - name: üè∑Ô∏è Set Version env variable
        run: echo "VERSION=$(bun run -c 'node -e \"console.log(require(\\\"./package.json\\\").version)\"')" >> $GITHUB_ENV

      - name: üè∑Ô∏è Set PACKAGE_NAME env variable
        run: echo "PACKAGE_NAME=$(ls -l | egrep -o "@rnrepo/expo-config-plugin-(.*)(=?\.tgz)")" >> $GITHUB_ENV

      - name: ‚ùå Fail if PACKAGE_NAME  and VERSION is not set
        if: ${{ env.PACKAGE_NAME == '' || env.VERSION == '' }}
        run: exit 1 # This should never happen.

      # - name: üè∑Ô∏è Create Git tag
      #   run: |
      #     git tag "expo-config-plugin-v${{ env.VERSION }}"
      #     git push origin "expo-config-plugin-v${{ env.VERSION }}"

      # TODO: Temporary use tag nightly
      - name: üöÄ Publish to npm
        run: npm publish $PACKAGE_NAME --tag nightly --provenance